name: Fix Template visual bug

on:
  push:
    branches: ["gh-pages-bugged"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "orange-500"
          replace: "yellow-500"
          regex: false
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.gh-pages }}
