name: Gatsby Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v1
#       - uses: enriikke/gatsby-gh-pages-action@v2
#         with:
#           access-token: ${{ secrets.ACCESS_TOKEN }}
#           deploy-branch: gh-pages
      - uses: actions/checkout@v2
        with:
          repository: 'jomcgi/personal-site'
          ref: 'gh-pages'
          token:  ${{ secrets.ACCESS_TOKEN }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "bg-orange-500"
          replace: "bg-yellow-500"
          regex: true
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
