name: Publish to github pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
      
      - name: Checkout develop
        uses: actions/checkout@v1
        with:
          ref: 'gh-pages'       

      - name: fix visual bug
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git config user.name "jomcgi"
          git config user.email "joe.mcginley2@gmail.com"
          # Gatsby template does not render bg-orange-500 for project status indicator
          git grep -l 'bg-orange-500' | xargs sed -i 's/bg-orange-500/bg-yellow-500/g'
          git commit -am "Fixed visual bug for personal-site deployment"
          git push
