name: Gatsby Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v1
#       - uses: enriikke/gatsby-gh-pages-action@v2
#         with:
#           access-token: ${{ secrets.ACCESS_TOKEN }}
#           deploy-branch: gh-pages

      - name: fix visual bug
        run: |
          git checkout gh-pages
          git pull
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git grep -l 'bg-orange-500' | xargs sed -i 's/bg-orange-500/bg-yellow-500/g'
          git commit -m "new date commit"
          git push origin gh-pages
