name: Gatsby Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v1
#       - uses: enriikke/gatsby-gh-pages-action@v2
#         with:
#           access-token: ${{ secrets.ACCESS_TOKEN }}
#           deploy-branch: gh-pages

      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: 'main'
      
      - name: Checkout develop
        uses: actions/checkout@v1
        with:
          ref: 'gh-pages'       

      - name: fix visual bug
        run: |
          git config user.name "jomcgi"
          git config user.email "joe.mcginley2@gmail.com"
          git grep -l 'bg-orange-500' | xargs sed -i 's/bg-orange-500/bg-yellow-500/g'
          git commit -am "Fixed visual bug for personal-site deployment"
          git push
